# Generated by Django 4.2.1 on 2023-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_brigade',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_operator',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('BRIGADE', 'Brigade'), ('CLIENT', 'Client')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
