# Generated by Django 4.2.1 on 2023-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_alter_user_username'),
        ('users', '0006_alter_client_managers_client_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='operator_profiles', to='auth.permission', verbose_name='Права доступа'),
        ),
    ]
