# Generated by Django 4.2.1 on 2023-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_brigade_managers_alter_client_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=1, max_length=60, unique=True, verbose_name='Адрес электронной почты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='email',
            field=models.EmailField(default=1, max_length=60, unique=True, verbose_name='Адрес электронной почты'),
            preserve_default=False,
        ),
    ]
