# Generated by Django 4.2.1 on 2023-05-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_client_email_operator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='operator',
        ),
    ]
