# Generated by Django 4.2.1 on 2023-05-19 07:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_brigade_remove_client_user_delete_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brigades_list',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True, verbose_name='Список участников бригады'),
        ),
    ]
