# Generated by Django 4.2.1 on 2023-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Установка экобокса', 'Установка экобокса'), ('Вывоз мусора', 'Вывоз мусора'), ('Демонтаж экобокса', 'Демонтаж экобокса')], default=None, max_length=25, verbose_name='Тип работ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В процессе', 'В процессе'), ('Выполнено', 'Выполнено')], default='Новая', max_length=20, verbose_name='Статус')),
                ('started_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('finished_application', models.DateTimeField(verbose_name='Дата закрытия')),
                ('finished_by_client', models.BooleanField(default=False, verbose_name='Отметить как Выпонено клиентом ')),
                ('finished_by_brigade', models.BooleanField(default=False, verbose_name='Отметить как Выпонено бригадой ')),
                ('finished_by_operator', models.BooleanField(default=False, verbose_name='Отметить как Выпонено оператором ')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
