# Generated by Django 4.2.1 on 2023-05-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='brigade',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'BRIGADE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_brigade', to=settings.AUTH_USER_MODEL, verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='application',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='application',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'OPERATOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор'),
        ),
    ]
