# Generated by Django 4.2.1 on 2023-05-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_Body',
            new_name='tutorial_body',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_Title',
            new_name='tutorial_title',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='tutorial_Video',
            new_name='tutorial_video',
        ),
    ]
