# Generated by Django 4.2.1 on 2023-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='finished_application',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата закрытия'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finished_by_brigade',
            field=models.BooleanField(default=None, verbose_name='Отметить как Выпонено бригадой '),
        ),
        migrations.AlterField(
            model_name='application',
            name='finished_by_client',
            field=models.BooleanField(default=None, verbose_name='Отметить как Выпонено клиентом '),
        ),
        migrations.AlterField(
            model_name='application',
            name='finished_by_operator',
            field=models.BooleanField(default=None, verbose_name='Отметить как Выпонено оператором '),
        ),
    ]
