# Generated by Django 4.2.1 on 2023-05-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_rename_tutorial_body_tutorial_tutorial_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Установка экобокса', 'Установка экобокса'), ('Вывоз мусора', 'Вывоз мусора'), ('Демонтаж экобокса', 'Демонтаж экобокса')], default=None, max_length=25, verbose_name='Тип работ')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('Новая', 'Новая'), ('В процессе', 'В процессе'), ('Выполнено', 'Выполнено')], default='Новая', max_length=20, verbose_name='Статус')),
                ('started_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата открытия')),
                ('finished_application', models.DateTimeField(verbose_name='Дата закрытия')),
                ('finished_by_client', models.BooleanField(default=False, verbose_name='Отметить как Выпонено клиентом ')),
                ('finished_by_brigade', models.BooleanField(default=False, verbose_name='Отметить как Выпонено бригадой ')),
                ('finished_by_operator', models.BooleanField(default=False, verbose_name='Отметить как Выпонено оператором ')),
                ('brigade', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'BRIGADE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_as_brigade', to=settings.AUTH_USER_MODEL, verbose_name='Бригада')),
                ('client', models.ForeignKey(limit_choices_to={'user_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_client', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('operator', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications_as_operator', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
