# Generated by Django 4.2.1 on 2023-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_finished_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='finished_by_brigade',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Отметить как Выпонено бригадой '),
        ),
        migrations.AlterField(
            model_name='application',
            name='finished_by_client',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Отметить как Выпонено клиентом '),
        ),
        migrations.AlterField(
            model_name='application',
            name='finished_by_operator',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Отметить как Выпонено оператором '),
        ),
    ]
